version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: geopass
      PGDATABASE: care_db
      PGPORT: 5432
      VIRTUAL_HOST: careapp.geostrategies.net
      LETSENCRYPT_HOST: careapp.geostrategies.net
      LETSENCRYPT_EMAIL: ftmn2001@yahoo.fr
    networks:
      - web
      - default
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npx", "nodemon", "index.js"]
    restart: unless-stopped

  db:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: geopass
      POSTGRES_DB: care_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
      - ./public/resources/Backup_BD:/backup

volumes:
  db-data:

networks:
  web:
    external: true   
